backend:
  name: github
  repo: katarzynakopcinska/PasjaPoProstu
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Produkty"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "desc", widget: "text"}
      - {label: "Zdjęcie", name: "image", widget: "image"}
