backend:
  name: github
  repo: katarzynakopcinska/PasjaPoProstu
  branch: main
  site_domain: thunderous-croquembouche-239589.netlify.app

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "produkty"
    label: "Produkty"
    folder: "produkty"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nazwa", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "text" }
      - { label: "ZdjÄ™cie", name: "image", widget: "image" }
